inertial_odometry:
  ros__parameters:
    imu_topic: /alpha/imu
    odometry_topic: /alpha/localisation/inertial/odometry
    filtered_imu_topic: /alpha/localisation/inertial/filtered_imu
    odom_frame: alpha/startup_fixed
    base_frame: alpha/base_link
    low_pass_cutoff_hz: 5.0
    gravity_mps2: 1.62
    remove_gravity: true
    maximum_dt_s: 0.25
    calibration_samples: 100
    acceleration_deadband_mps2: 0.02
    angular_rate_deadband_radps: 0.002
