alpha_driver_node:
  ros__parameters:
    noise_enabled: true
    random_seed: 7302028
    raw_imu_topic: /alpha/raw/imu
    imu_topic: /alpha/imu
    imu_angular_velocity_stddev_radps: 0.008
    imu_linear_acceleration_stddev_mps2: 0.05
    imu_orientation_stddev_rad: 0.003
    imu_angular_velocity_bias_radps:
    - 0.002
    - -0.001
    - 0.0015
    imu_linear_acceleration_bias_mps2:
    - 0.02
    - -0.015
    - 0.025
    raw_joint_state_topic: /alpha/raw/joint_states
    joint_state_topic: /alpha/joint_states
    wheel_position_stddev_rad: 0.002
    wheel_velocity_stddev_radps: 0.015
    camera_pixel_stddev: 6.0
